zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    search-service: /films/**
    api-gateway: /gateway/**

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

# Internationalization
spring.messages.basename: messages/messages

---
spring:
  config:
    activate:
      on-profile: docker
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://starwar-discovery-server:8761/eureka/
management:
  tracing:
    sampling:
      probability: 1.0  # Sample 100% of traces (adjust as needed)
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans  # Use the Kubernetes Service name for Zipkin
