spring:
  config:
    activate:
      on-profile: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8081
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://starwar-discovery-server:8761/eureka/
management:
  tracing:
    sampling:
      probability: 1.0  # Sample 100% of traces (adjust as needed)
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans  # Use the Kubernetes Service name for Zipkin
